
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pl' | 'no' | 'en';

interface TranslationSructure {
  [key: string]: {
    [key in Language]: string;
  };
}

export const translations: TranslationSructure = {
  // Navigation
  'nav.home': { pl: 'Start', no: 'Hjem', en: 'Home' },
  'nav.about': { pl: 'O nas', no: 'Om oss', en: 'About Us' },
  'nav.projects': { pl: 'Projekty i Galerie', no: 'Prosjekter og Gallerier', en: 'Projects & Galleries' },
  'nav.branches': { pl: 'Oddziały regionalne', no: 'Regionale avdelinger', en: 'Regional Branches' },
  'nav.membership': { pl: 'Członkostwo', no: 'Medlemskap', en: 'Membership' },
  'nav.contact': { pl: 'Kontakt', no: 'Kontakt', en: 'Contact' },
  'nav.join': { pl: 'Dołącz do nas', no: 'Bli med oss', en: 'Join Us' },
  'nav.grants': { pl: 'Dotacje i Wsparcie', no: 'Støtteordninger', en: 'Grants & Support' },
  'nav.events': { pl: 'Wydarzenia', no: 'Arrangementer', en: 'Events' },

  // Common
  'common.branches': { pl: 'Filie regionalne', no: 'Regionale filialer', en: 'Regional Branches' },
  'common.visitFacebook': { pl: 'Odwiedź nas', no: 'Besøk oss', en: 'Visit us' },
  'common.email': { pl: 'Napisz do nas', no: 'Send oss e-post', en: 'Email us' },
  'common.readMore': { pl: 'Czytaj więcej', no: 'Les mer', en: 'Read more' },
  'common.joinCommunity': { pl: 'Dołącz do wspólnoty', no: 'Bli med i fellesskapet', en: 'Join the community' },
  'common.contactUs': { pl: 'Skontaktuj się z nami', no: 'Kontakt oss', en: 'Contact us' },
  'common.norway': { pl: 'Norwegia', no: 'Norge', en: 'Norway' },
  'common.group': { pl: 'Grupa', no: 'Gruppe', en: 'Group' },
  'common.back': { pl: 'Wróć', no: 'Tilbake', en: 'Back' },

  // Home Page
  'home.subtitle': { pl: 'Odkrywamy pasje, łączymy talenty', no: 'Oppdager lidenskaper, forener talenter', en: 'Discovering passions, uniting talents' },
  'home.quote': { pl: 'Skandias Talentsmie to miejsce, gdzie rodzi się twórczość, a tradycja spotyka się z nowoczesnością. Nasza kuźnia to nie tylko warsztaty – to społeczność ludzi pełnych pasji, którzy wspólnie tworzą przyszłość rzemiosła i sztuki w Norwegii.', no: 'Skandias Talentsmie er et sted hvor kreativitet blir født, og tradisjon møter modernitet. Vår smie er ikke bare workshoper – det er et fellesskap av lidenskapelige mennesker som sammen skaper fremtiden for håndverk og kunst i Norge.', en: 'Skandias Talentsmie is a place where creativity is born, and tradition meets modernity. Our forge is not just workshops – it is a community of passionate people who together create the future of craft and art in Norway.' },
  'home.missionBtn': { pl: 'Nasza misja', no: 'Vårt oppdrag', en: 'Our Mission' },
  'home.fbGroup': { pl: 'Grupa na Facebooku', no: 'Facebook-gruppe', en: 'Facebook Group' },
  'home.fbFollow': { pl: 'Śledź nas na FB', no: 'Følg oss på FB', en: 'Follow us on FB' },
  'home.features.passion.title': { pl: 'Pasja i Twórczość', no: 'Lidenskap og kreativitet', en: 'Passion & Creativity' },
  'home.features.passion.desc': { pl: 'Miejsce dla każdego, kto chce rozwijać swój talent.', no: 'Et sted for alle som ønsker å utvikle sitt talent.', en: 'A place for everyone who wants to develop their talent.' },
  'home.features.community.title': { pl: 'Silna Społeczność', no: 'Sterkt fellesskap', en: 'Strong Community' },
  'home.features.community.desc': { pl: 'Łączymy artystów i rzemieślników w całej Norwegii.', no: 'Vi forener kunstnere og håndverkere over hele Norge.', en: 'We unite artists and craftspeople throughout Norway.' },
  'home.features.growth.title': { pl: 'Rozwój i Promocja', no: 'Utvikling og promotering', en: 'Growth & Promotion' },
  'home.features.growth.desc': { pl: 'Pomagamy promować Twoją twórczość i zdobywać nowe umiejętności.', no: 'Vi hjelper med å promotere ditt arbeid og tilegne deg nye ferdigheter.', en: 'We help promote your work and acquire new skills.' },
  'home.news.title': { pl: 'Aktualności', no: 'Nyheter', en: 'News' },
  'home.news.more': { pl: 'Zobacz wszystkie', no: 'Se alle', en: 'See all' },
  'home.news.item1.title': { pl: 'Pierwsza filia Agder już działa!', no: 'Den pierwsza Agder-filialen er i drift!', en: 'The first Agder branch is now active!' },
  'home.news.item1.tag': { pl: 'Ważne', no: 'Viktig', en: 'Important' },
  'home.news.item2.title': { pl: 'Warsztaty makramy w Oslo - zapisy otwarte', no: 'Makramé-workshop i Oslo - påmeldingen er åpen', en: 'Macrame workshops in Oslo - registration open' },
  'home.news.item2.tag': { pl: 'Warsztaty', no: 'Workshop', en: 'Workshop' },
  'home.news.item3.title': { pl: 'Nowy projekt "Słowiańska Kuźnia" 13x13', no: 'Nytt prosjekt «Slavisk Smie» 13x13', en: 'New project "Slavic Forge" 13x13' },
  'home.news.item3.tag': { pl: 'Projekt', no: 'Prosjekt', en: 'Project' },
  'home.vision': { pl: 'Kultura to nie tylko piękne przedmioty, to przede wszystkim więzi, które tworzymy, pracując ramie w ramie.', no: 'Kultur er ikke bare vakre gjenstander, det er fremfor alt båndene vi skaper når vi jobber side om side.', en: 'Culture is not just beautiful objects, it is above all the bonds we create working side by side.' },
  'home.joinCommunity': { pl: 'Dołącz do wspólnoty', no: 'Bli med i fellesskapet', en: 'Join the community' },
  'home.branches.title': { pl: 'Nasze oddziały', no: 'Våre avdelinger', en: 'Our Branches' },
  'home.branches.subtitle': { pl: '12 filii regionalnych Skandias Talentsmie', no: '12 regionale avdelinger av Skandias Talentsmie', en: '12 regional branches of Skandias Talentsmie' },
  'home.branches.more': { pl: 'Zobacz szczegóły oddziałów', no: 'Se detaljer om avdelinger', en: 'See branch details' },
  'home.branches.norway': { pl: 'w całej Norwegii', no: 'i hele Norge', en: 'throughout Norway' },
  'home.footer.quote': { pl: '"Kuźnia, w której hartujemy nie tylko rękodzieło i sztukę, ale także wiezi międzyludzkie."', no: '"En smie hvor vi herder ikke bare håndverk og kunst, men også mellommenneskelige bånd."', en: '"A forge where we temper not only handicrafts and art, but also human bonds."' },
  'home.footer.copy': { pl: 'Pielęgnujemy Tradycję', no: 'Vi pleier tradisjonen', en: 'Nurturing Tradition' },

  // Events Page
  'events.title': { pl: 'Aktualne wydarzenia', no: 'Aktuelle arrangementer', en: 'Current Events' },
  'events.subtitle': { pl: 'Aktualny kalendarz warsztatów, kiermaszy i spotkań w całej Norwegii. Dołącz do nas i twórz na żywo!', no: 'Aktuell kalender for workshoper, messer og møter i hele Norge. Bli med oss og skap live!', en: 'Current calendar of workshops, fairs and meetings throughout Norway. Join us and create live!' },
  'events.searchPlaceholder': { pl: 'Szukaj wydarzenia...', no: 'Søk etter arrangement...', en: 'Search events...' },
  'events.viewGallery': { pl: 'Zobacz galerię', no: 'Se galleri', en: 'View gallery' },
  'events.upcoming': { pl: 'Nadchodzące wydarzenia', no: 'Kommende arrangementer', en: 'Upcoming Events' },
  'events.past': { pl: 'Minione wydarzenia', no: 'Tidligere arrangementer', en: 'Past Events' },
  'events.allRegions': { pl: 'Wszystkie regiony', no: 'Alle regioner', en: 'All regions' },
  'events.noResults': { pl: 'Brak wydarzeń spełniających kryteria.', no: 'Ingen arrangementer funnet som samsvarer med kriteriene.', en: 'No events matching the criteria.' },
  'events.details': { pl: 'Szczegóły wydarzenia', no: 'Detaljer om arrangementet', en: 'Event details' },
  'events.date': { pl: 'Data', no: 'Dato', en: 'Date' },
  'events.time': { pl: 'Godzina', no: 'Tid', en: 'Time' },
  'events.location': { pl: 'Lokalizacja', no: 'Sted', en: 'Location' },
  'events.address': { pl: 'Adres', no: 'Adresse', en: 'Address' },
  'events.gallery': { pl: 'Galeria zdjęć', no: 'Bildegalleri', en: 'Photo gallery' },
  'events.gallerySubtitle': { pl: 'Zapraszamy do obejrzenia zdjęć z tego wydarzenia.', no: 'Velkommen til å se bildene fra dette arrangementet.', en: 'Welcome to view the photos from this event.' },
  'events.back': { pl: 'Wróć do listy', no: 'Tilbake til listen', en: 'Back to list' },
  'events.comingSoon.title': { pl: 'Kolejne terminy wkrótce', no: 'Nye datoer kommer snart', en: 'New dates coming soon' },
  'events.comingSoon.subtitle': { pl: '"Cierpliwość rzemieślnika to połowa sukcesu. Pracujemy nad wdrożeniem pełnego kalendarza na rok 2026."', no: '"Håndverkerens tålmodighet er halve suksessen. Vi jobber med å implementere den fulle kalenderen for 2026."', en: '"A craftsman\'s patience is half the success. We are working on implementing the full calendar for 2026."' },
  'events.comingSoon.button': { pl: 'Wkrótce nowe warsztaty', no: 'Nye workshoper kommer snart', en: 'New workshops coming soon' },
  'events.gallery.close': { pl: 'Zamknij galerię', no: 'Lukk galleri', en: 'Close gallery' },

  // Projects Page
  'projects.title': { pl: 'Projekty i pomysły', no: 'Prosjekter og ideer', en: 'Projects & Ideas' },
  'projects.subtitle': { pl: 'Skandias Talentsmie to miejsce, gdzie Twój pomysł może stać się rzeczywistością. Zgłoś swoją inicjatywę! Razem przekujemy marzenia w czyn.', no: 'Skandias Talentsmie er et sted hvor din idé kan bli virkelighet. Meld inn ditt initiativ! Sammen gjør vi drømmer til handling.', en: 'Skandias Talentsmie is a place where your idea can become reality. Submit your initiative! Together we turn dreams into action.' },
  'projects.addTitle': { pl: 'Dodaj swój pomysł', no: 'Legg til din idé', en: 'Add your idea' },
  'projects.addDesc': { pl: 'Masz wizję na nowe warsztaty? Chciałbyś zorganizować kiermasz w swoim mieście? Wypełnij krótki formularz, a my pomożemy Ci to zrealizować.', no: 'Har du en visjon for nye workshoper? Vil du arrangere et marked i byen din? Fyll ut et kort skjema, så hjelper vi deg å realisere det.', en: 'Do you have a vision for new workshops? Would you like to organize a fair in your city? Fill out a short form, and we will help you realize it.' },
  'projects.addBtn': { pl: 'Formularz zgłoszeniowy', no: 'Søknadsskjema', en: 'Application form' },
  'projects.grantsTitle': { pl: 'Granty i wsparcie', no: 'Stipend og støtte', en: 'Grants & Support' },
  'projects.grantsDesc': { pl: 'Pomagamy naszym członkom w uzyskiwaniu dofinansowań i grantów na cele artystyczno-kulturalne. Nasz zespół finansowy służy wsparciem w formalnościach.', no: 'Vi hjelper våre medlemmer med å få finansiering og stipend til kunstneriske og kulturelle formål. Vårt økonomiteam hjelper med formalitetene.', en: 'We help our members obtain funding and grants for artistic and cultural purposes. Our finance team provides support with formalities.' },
  'projects.grantsBtn': { pl: 'Dowiedz się więcej', no: 'Finn ut mer', en: 'Learn more' },
  'projects.planningTitle': { pl: 'Co obecnie planujemy?', no: 'Hva planlegger vi nå?', en: 'What are we planning now?' },
  'projects.activeTag': { pl: 'Projekt Aktywny ❦', no: 'Aktivt prosjekt ❦', en: 'Active Project ❦' },
  'projects.list.1': { pl: '13 x 13: Sieć 13 filii regonanych', no: '13 x 13: Nettverk av 13 regionale avdelinger', en: '13 x 13: Network of 13 regional branches' },
  'projects.list.2': { pl: 'Centrum Songe: Przebudowa pracowni', no: 'Songe-senteret: Ombygging av verkstedet', en: 'Songe Center: Workshop reconstruction' },
  'projects.list.3': { pl: 'Słowiański Jarmark Julemarked', no: 'Slavisk Julemarked', en: 'Slavic Christmas Market' },

  // Contact Page
  'contact.title': { pl: 'Napisz do nas', no: 'Skriv til oss', en: 'Write to us' },
  'contact.subtitle': { pl: 'Masz pytania? Chcesz do nas dołączyć? Wypełnij nasz formularz zgłoszeniowy lub skontaktuj się z nami bezpośrednio.', no: 'Har du spørsmål? Vil du bli med oss? Fyll ut vårt søknadsskjema eller kontakt oss direkte.', en: 'Do you have questions? Do you want to join us? Fill out our application form or contact us directly.' },
  'contact.formTitle': { pl: 'Formularz kontaktu', no: 'Kontaktskjema', en: 'Contact Form' },
  'contact.joinTitle': { pl: 'Dołącz do nas!', no: 'Bli med oss!', en: 'Join us!' },
  'contact.joinDesc': { pl: 'Najszybszym sposobem na kontakt z nami i zgłoszenie chęci dołączenia jest nasz oficjalny formularz Google. Kliknij poniższy przycisk, aby go otworzyć.', no: 'Den raskeste måten å kontakte oss på og melde din interesse er vårt offisielle Google-skjema. Klikk på knappen nedenfor for å åpne det.', en: 'The fastest way to contact us and express interest is our official Google form. Click the button below to open it.' },
  'contact.openForm': { pl: 'Otwórz formularz zgłoszeniowy', no: 'Åpne søknadsskjemaet', en: 'Open application form' },
  'contact.formNote': { pl: 'Formularz otworzy się w nowej karcie (Google Forms).', no: 'Skjemaet åpnes i en ny fane (Google Forms).', en: 'The form will open in a new tab (Google Forms).' },
  'contact.infoTitle': { pl: 'Informacje', no: 'Informasjon', en: 'Information' },
  'contact.mainEmail': { pl: 'Główny e-mail', no: 'Hoved-e-post', en: 'Main Email' },
  'contact.facebook': { pl: 'Facebook', no: 'Facebook', en: 'Facebook' },
  'contact.mainAddress': { pl: 'Adres główny', no: 'Hovedadresse', en: 'Main Address' },
  'contact.deptEmails': { pl: 'E-maile filii i działów:', no: 'E-poster til avdelinger:', en: 'Branch and dept emails:' },
  'contact.dept.membership': { pl: 'Członkostwo', no: 'Medlemskap', en: 'Membership' },
  'contact.dept.finance': { pl: 'Finanse', no: 'Økonomi', en: 'Finance' },
  'contact.dept.projects': { pl: 'Projekty', no: 'Prosjekter', en: 'Projects' },
  'contact.dept.note': { pl: 'Dla każdego województwa: [wojewodztwo]@skandiatalentsmie.no', no: 'For hvert fylke: [fylke]@skandiatalentsmie.no', en: 'For each county: [county]@skandiatalentsmie.no' },

  // Branches Page
  'branches.structure': { pl: 'Struktura stowarzyszenia', no: 'Foreningens struktur', en: 'Association structure' },
  'branches.title': { pl: 'Nasze Filie i Oddziały', no: 'Våre filialer og avdelinger', en: 'Our Branches & Departments' },
  'branches.subtitle': { pl: 'Skandias Talentsmie to ogólnonorweska „Kuźnia Matka”, pod której skrzydłami działa 12 wyspecjalizowanych oddziałów regionalnych. Znajdź swoją najbliższą filię! 🇳🇴', no: 'Skandias Talentsmie er en landsdekkende «morsmie», med 12 spesialiserte regionale avdelinger. Finn din nærmeste filial! 🇳🇴', en: 'Skandias Talentsmie is a nationwide "Mother Forge", under whose wings 12 specialized regional branches operate. Find your nearest branch! 🇳🇴' },
  'branches.branchLabel': { pl: 'Skandias Talentsmie Branch', no: 'Skandias Talentsmie avdeling', en: 'Skandias Talentsmie Branch' },
  'branches.gatheringArtists': { pl: 'Skupia artystów z miast:', no: 'Samler kunstnere fra byene:', en: 'Gathers artists from cities:' },
  'branches.discover': { pl: 'Odkryj filię', no: 'Oppdag avdelingen', en: 'Discover the branch' },
  'branches.missingRegion.title': { pl: 'Nie widzisz swojego regionu?', no: 'Ser du ikke din region?', en: 'Don\'t see your region?' },
  'branches.missingRegion.desc': { pl: 'Stale rośniemy! Jeśli chciałbyś zostać koordynatorem w nowym miejscu lub pomóc w rozwoju istniejącej filii – napisz do nas. Razem możemy więcej.', no: 'Vi vokser stadig! Hvis du ønsker å bli koordinator på et nytt sted eller bidra til utviklingen av en eksisterende filial – skriv til oss. Sammen kan vi gjøre mer.', en: 'We are constantly growing! If you would like to become a coordinator in a new place or help develop an existing branch – write to us. Together we can do more.' },
  'branches.missingRegion.btn': { pl: 'Dowiedz się o koordynatorach', no: 'Lær om koordinatorer', en: 'Learn about coordinators' },

  // Branch Page
  'branch.notFound': { pl: 'Filia nie została znaleziona', no: 'Avdelingen ble ikke funnet', en: 'Branch not found' },
  'branch.backHome': { pl: 'Wróć do strony głównej', no: 'Tilbake til startsiden', en: 'Back to home page' },
  'branch.region': { pl: 'Region:', no: 'Region:', en: 'Region:' },
  'branch.gatheringDesc': { pl: 'Nasza filia w regionie {name} to miejsce spotkań artystów i rzemieślników z miast: {cities}.', no: 'Vår filial i regionen {name} er et møtested for kunstnere og håndverkere fra byene: {cities}.', en: 'Our branch in the {name} region is a meeting place for artists and craftspeople from the cities: {cities}.' },
  'branch.aboutTitle': { pl: 'O działalności', no: 'Om virksomheten', en: 'About activities' },
  'branch.description': { pl: 'W województwie {name} skupiamy się na jednoczeniu lokalnej społeczności Słowian poprzez warsztaty rzemieślnicze i wystawy. Promujemy lokalne talenty i pomagamy artystom w budowaniu ich rozpoznawalności w Norwegii.', no: 'I fylket {name} fokuserer vi på å forene det lokale slaviske samfunnet gjennom håndverksverksteder og utstillinger. Vi fremmer lokale talenter og hjelper kunstnere med å bygge sin anerkjennelse i Norge.', en: 'In the {name} county, we focus on uniting the local Slavic community through craft workshops and exhibitions. We promote local talents and help artists build their recognition in Norway.' },
  'branch.eventsTitle': { pl: 'Wydarzenia w regionie', no: 'Arrangementer i regionen', en: 'Events in the region' },
  'branch.upcomingMeeting': { pl: 'Nadchodzące spotkanie', no: 'Kommende møte', en: 'Upcoming meeting' },
  'branch.meetingName': { pl: 'Spotkanie zapoznawcze', no: 'Bli-kjent-møte', en: 'Introductory meeting' },
  'branch.locationLabel': { pl: 'Miejsce:', no: 'Sted:', en: 'Location:' },
  'branch.online': { pl: 'Online', no: 'Online', en: 'Online' },
  'branch.noEvents': { pl: 'Brak innych zaplanowanych wydarzeń w najbliższym czasie.', no: 'Ingen andre planlagte arrangementer i nær fremtid.', en: 'No other scheduled events in the near future.' },
  'branch.galleryTitle': { pl: 'Galeria z eventów', no: 'Galleri fra arrangementer', en: 'Gallery from events' },
  'branch.viewAll': { pl: 'Zobacz wszystkie', no: 'Se alle', en: 'View all' },
  'branch.previewWorks': { pl: 'Podgląd prac', no: 'Forhåndsvisning av verk', en: 'Work preview' },
  'branch.actionTitle': { pl: 'Chcesz działać w tym regionie?', no: 'Vil du være aktiv i denne regionen?', en: 'Want to be active in this region?' },
  'branch.actionDesc': { pl: 'Szukamy wolontariuszy, artystów i osób, które pomogą nam rozwijać lokalną filię. Każda pomoc i każdy talent są na wagę złota.', no: 'Vi søker frivillige, kunstnere og folk som vil hjelpe oss med å utvikle den lokale filialen. All hjelp og alle talenter er gull verdt.', en: 'We are looking for volunteers, artists, and people to help us develop the local branch. Every help and every talent is worth its weight in gold.' },
  'branch.contactBtn': { pl: 'Skontaktuj się z nami', no: 'Kontakt oss', en: 'Contact us' },

  // Grants Info Page
  'grants.back': { pl: 'Powrót do projektów', no: 'Tilbake til prosjekter', en: 'Back to projects' },
  'grants.title': { pl: 'Granty i wsparcie', no: 'Stipend og støtte', en: 'Grants & Support' },
  'grants.subtitle': { pl: 'Szczegółowe informacje o celach, lokalizacji i wpływie społecznym Skandias Talentsmie.', no: 'Detaljert informasjon om mål, plassering og samfunnspåvirkning av Skandias Talentsmie.', en: 'Detailed information about goals, location, and social impact of Skandias Talentsmie.' },
  'grants.geo.title': { pl: 'Geografia i lokalizacja', no: 'Geografi og beliggenhet', en: 'Geography & Location' },
  'grants.geo.desc1': { pl: 'Stowarzyszenie Skandias Talentsmie jest formalnie zarejestrowane w Grimstad, czyli w regionie Agder, a od dnia 16 października 2025 roku przejmie nową, stałą siedzibę w Songe (Sliperikleiva 2, gmina Tvedestrand, Agder).', no: 'Foreningen Skandias Talentsmie er formelt registrert i Grimstad, i Agder-regionen, og fra 16. oktober 2025 vil den overta et nytt, permanent hovedkvarter i Songe (Sliperikleiva 2, Tvedestrand kommune, Agder).', en: 'The Skandias Talentsmie association is formally registered in Grimstad, in the Agder region, and as of October 16, 2025, it will take over a new, permanent headquarters in Songe (Sliperikleiva 2, Tvedestrand municipality, Agder).' },
  'grants.geo.desc2': { pl: 'Dzięki temu projekt będzie realizowany w pełni na obszarze objętym programem – Agder i Telemark. Nasza lokalizacja spełnia więc wszystkie wymagania geograficzne i zapewnia, że działania będą dostępne zarówno dla mieszkańców Agder, jak i dla społeczności z sąsiedniego regionu Telemark.', no: 'Takket være dette vil prosjektet bli fullstendig gjennomført i området dekket av programmet – Agder og Telemark. Vår plassering oppfyller dermed alle geografiske krav og sikrer at aktivitetene vil være tilgjengelige for både innbyggere i Agder og for lokalsamfunnet i naboregionen Telemark.', en: 'Thanks to this, the project will be fully implemented in the area covered by the program – Agder and Telemark. Our location thus meets all geographical requirements and ensures that activities will be available to both Agder residents and the community in the neighboring Telemark region.' },
  'grants.geo.quote': { pl: '"Posiadanie własnej nieruchomości w Songe daje nam gwarancję trwałości i ciągłości działań, a jednocześnie mocno osadza projekt w lokalnej społeczności regionu Agder."', no: '«Å eie egen eiendom i Songe gir oss en garanti for bærekraft og kontinuitet i aktivitetene, samtidig som det forankrer prosjektet sterkt i lokalsamfunnet i Agder-regionen.»', en: '"Owning our own property in Songe gives us a guarantee of sustainability and continuity of actions, while at the same time strongly embedding the project in the local community of the Agder region."' },
  'grants.formal.title': { pl: 'Spełnienie kryteriów formalnych', no: 'Oppfyllelse av formelle kriterier', en: 'Meeting formal criteria' },
  'grants.formal.status.title': { pl: 'Status prawny', no: 'Rettslig status', en: 'Legal status' },
  'grants.formal.status.list1': { pl: 'Jesteśmy stowarzyszeniem (forening) zarejestrowanym w Brønnøysundregistrene – Enhetsregisteret.', no: 'Vi er en forening registrert i Brønnøysundregistrene – Enhetsregisteret.', en: 'We are an association (forening) registered in Brønnøysundregistrene – Enhetsregisteret.' },
  'grants.formal.status.list2': { pl: 'Posiadamy własny numer organizacyjny i działamy zgodnie z Frivillighetsregisterloven.', no: 'Vi har vårt eget organisasjonsnummer og opererer i samsvar med Frivillighetsregisterloven.', en: 'We have our own organization number and operate in accordance with Frivillighetsregisterloven.' },
  'grants.formal.status.list3': { pl: 'Jesteśmy organizacją non-profit – całość środków jest przeznaczana na cele statutowe.', no: 'Vi er en ideell organisasjon – alle midler brukes til vedtektsfestede formål.', en: 'We are a non-profit organization – all funds are used for statutory purposes.' },
  'grants.formal.contribution.title': { pl: 'Unikalny wkład', no: 'Unikt bidrag', en: 'Unique contribution' },
  'grants.formal.contribution.list1': { pl: 'Brak powielania zadań sektora publicznego (nie zastępujemy szkół ani NAV).', no: 'Ingen duplisering av offentlige oppgaver (vi erstatter ikke skoler eller NAV).', en: 'No duplication of public sector tasks (we do not replace schools or NAV).' },
  'grants.formal.contribution.list2': { pl: 'Oferujemy aktywności kulturalne i integracyjne, które są dobrowolne i dodatkowe.', no: 'Vi tilbyr kulturelle og integrerende aktiviteter som er frivillige og i tillegg.', en: 'We offer cultural and integrative activities that are voluntary and additional.' },
  'grants.formal.contribution.list3': { pl: 'Tworzymy sieć synergii między organizacjami w regionie.', no: 'Vi skaper et nettverk av synergier mellom organisasjonene i regionen.', en: 'We create a network of synergies between organizations in the region.' },
  'grants.volunteers.title': { pl: 'Serce projektu: Wolontariusze', no: 'Prosjektets hjerte: Frivillige', en: 'Heart of the project: Volunteers' },
  'grants.volunteers.desc': { pl: 'Bez wolontariuszy Skandias Talentsmie nie miałoby sensu. To oni malują pierwsze dekoracje, szykują sale, uczą innych, dzielą się swoją wiedzą i czasem.', no: 'Uten frivillige ville ikke Skandias Talentsmie hatt noen mening. Det er de som maler de første dekorasjonene, gjør klar rommene, underviser andre, og deler sin kunnskap og tid.', en: 'Without volunteers, Skandias Talentsmie would have no meaning. It is they who paint the first decorations, prepare the rooms, teach others, and share their knowledge and time.' },
  'grants.volunteers.fund.title': { pl: 'Fundusz Godzin i Dojazdów', no: 'Fond for timer og reiseutgifter', en: 'Hours & Travel Fund' },
  'grants.volunteers.fund.desc': { pl: 'Zwroty kosztów, by nikt nie musiał dopłacać z własnej kieszeni.', no: 'Refusjon av utgifter slik at ingen må betale fra egen lomme.', en: 'Expense reimbursements so no one has to pay out of pocket.' },
  'grants.volunteers.academy.title': { pl: 'Akademia Wolontariatu', no: 'Frivillighetsakademi', en: 'Volunteer Academy' },
  'grants.volunteers.academy.desc': { pl: 'Szkolenia, certyfikacja i nowe kompetencje na lata.', no: 'Opplæring, sertifisering og ny kompetanse for årene som kommer.', en: 'Training, certification, and new competencies for years to come.' },
  'grants.volunteers.workshop.title': { pl: 'Wyposażenie pracowni', no: 'Verkstedutstyr', en: 'Workshop equipment' },
  'grants.volunteers.workshop.desc': { pl: 'Profesjonalne narzędzia i bezpieczne stanowiska pracy.', no: 'Profesjonelle verktøy og trygge arbeidsstasjoner.', en: 'Professional tools and safe workstations.' },
  'grants.volunteers.coordination.title': { pl: 'Koordynacja i opieka', no: 'Koordinering og omsorg', en: 'Coordination & care' },
  'grants.volunteers.coordination.desc': { pl: 'Spójny system wsparcia, by nikt nie "zginął w tłumie".', no: 'Et sammenhengende støttesystem slik at ingen «drukner i mengden».', en: 'A coherent support system so no one "gets lost in the crowd".' },
  'grants.assets.title': { pl: 'Realna baza i stabilność', no: 'Reell base og stabilitet', en: 'Real assets & stability' },
  'grants.assets.desc': { pl: 'Zakupiliśmy nieruchomość w Songe ze środków własnych członków. To inwestycja, która pokazuje naszą wiarę w długofalowy rozwój.', no: 'Vi kjøpte eiendommen i Songe med egne midler fra medlemmene. Det er en investering som viser vår tro på langsiktig utvikling.', en: 'We purchased the property in Songe with our members\' own funds. It is an investment that shows our faith in long-term development.' },
  'grants.assets.a': { pl: 'Nowy budynek z 2009 roku (dawne przedszkole) – centrum warsztatowe.', no: 'Nytt bygg fra 2009 (tidligere barnehage) – verkstedsenter.', en: 'New building from 2009 (former kindergarten) – workshop center.' },
  'grants.assets.b': { pl: 'Stary dom z 1900 roku – przestrzeń inspiracji łącząca tradycję z nowoczesnością.', no: 'Gammelt hus fra 1900 – et rom for inspirasjon som kombinerer tradisjon med modernitet.', en: 'Old house from 1900 – an inspiration space combining tradition with modernity.' },
  'grants.action.title': { pl: 'Co już robimy?', no: 'Hva gjør vi allerede?', en: 'What are we doing already?' },
  'grants.action.jarmark.title': { pl: 'Jarmark Bożonarodzeniowy', no: 'Julemarked', en: 'Christmas Market' },
  'grants.action.jarmark.desc': { pl: 'Wydarzenie w filii Landvik Skomle z ogromnym zainteresowaniem lokalnej społeczności.', no: 'Arrangement i Landvik Skomle-avdelingen med stor interesse fra lokalsamfunnet.', en: 'Event in the Landvik Skomle branch with huge interest from the local community.' },
  'grants.action.collab.title': { pl: 'Współpraca instytucjonalna', no: 'Institusjonelt samarbeid', en: 'Institutional collaboration' },
  'grants.action.collab.desc': { pl: 'Regularnie współpracujemy z instytucjami publicznymi, budując sieć partnerstw.', no: 'Vi samarbeider regelmessig med offentlige institusjoner og bygger et nettverk av partnerskap.', en: 'We regularly collaborate with public institutions, building a network of partnerships.' },
  'grants.results.title': { pl: 'Mierzalne rezultaty (Rok 1)', no: 'Målbare resultater (År 1)', en: 'Measurable results (Year 1)' },
  'grants.results.subtitle': { pl: 'Nasze cele na najbliższy czas są konkretne i ambitne.', no: 'Våre mål for den nærmeste fremtiden er konkrete og ambisiøse.', en: 'Our goals for the near future are concrete and ambitious.' },
  'grants.results.participants': { pl: 'Uczestników warsztatów', no: 'Workshop-deltakere', en: 'Workshop participants' },
  'grants.results.works': { pl: 'Wystawionych prac', no: 'Utstilte verk', en: 'Exhibited works' },
  'grants.results.wellbeing': { pl: 'Wzrost dobrostanu', no: 'Økt velvære', en: 'Well-being growth' },
  'grants.results.partnerships': { pl: 'Partnerstw lokalnych', no: 'Lokale partnerskap', en: 'Local partnerships' },
  'grants.enable.title': { pl: 'Co umożliwiamy?', no: 'Hva muliggjør vi?', en: 'What do we enable?' },
  'grants.enable.list1': { pl: 'Scena i widoczność dla twórców (wystawy, jarmarki).', no: 'Scene og synlighet for skapere (utstillinger, markeder).', en: 'Stage and visibility for creators (exhibitions, fairs).' },
  'grants.enable.list2': { pl: 'Kompetencje twórcze i „okołozawodowe” (wycena, marketing).', no: 'Kreativ og «yrkesnær» kompetanse (prising, markedsføring).', en: 'Creative and "vocational" skills (pricing, marketing).' },
  'grants.enable.list3': { pl: 'Most pokoleń: seniorzy jako mistrzowie tradycji.', no: 'Generasjonsbro: eldre som tradisjonsmestre.', en: 'Generation bridge: seniors as tradition masters.' },
  'grants.enable.list4': { pl: '„Norweski w ruchu”: nauka języka przy rzemiośle.', no: '«Norsk i bevegelse»: språklæring gjennom håndverk.', en: '"Norwegian in motion": language learning through crafts.' },
  'grants.why.title': { pl: 'Dlaczego my?', no: 'Hvorfor oss?', en: 'Why us?' },
  'grants.why.list1': { pl: 'Federacyjność: model Agder to pilotaż dla całej Norwegii.', no: 'Føderal modell: Agder-modellen er en pilot for hele Norge.', en: 'Federalism: the Agder model is a pilot for all of Norway.' },
  'grants.why.list2': { pl: 'Etyka i ekologia: recykling i naprawa.', no: 'Etikk og økologi: resirkulering og reparasjon.', en: 'Ethics and ecology: recycling and repair.' },
  'grants.why.list3': { pl: 'Godność twórcy: uświadamianie wartości pracy rąk.', no: 'Skaperens verdighet: bevisstgjøring av verdien av manuelt arbeid.', en: 'Creator\'s dignity: raising awareness of the value of hand work.' },
  'grants.why.list4': { pl: 'Trwałość: własna siedziba gwarantuje ciągłość.', no: 'Bærekraft: eget hovedkvarter sikrer kontinuitet.', en: 'Sustainability: own headquarters guarantees continuity.' },
  'grants.budget.title': { pl: 'Budżet i finansowanie (3 lata)', no: 'Budsjett og finansiering (3 år)', en: 'Budget & funding (3 years)' },
  'grants.budget.total': { pl: '750.000 NOK', no: '750.000 NOK', en: '750,000 NOK' },
  'grants.budget.desc': { pl: 'Całkowity budżet projektu wynosi 750.000 NOK. Każda korona jest inwestycją w trwały mechanizm zmiany społecznej.', no: 'Det totale budsjettet for prosjektet er 750.000 NOK. Hver krone er en investering i en varig mekanisme for sosial endring.', en: 'The total project budget is 750,000 NOK. Every krone is an investment in a lasting mechanism for social change.' },
  'grants.budget.item1.title': { pl: 'Adaptacja przestrzeni', no: 'Tilpasning av lokaler', en: 'Space adaptation' },
  'grants.budget.item1.desc': { pl: 'Remont sali głównej, wyposażenie pracowni, kuchni i altan w ogrodzie.', no: 'Renovering av hovedsalen, utstyr til verksted, kjøkken og lysthus i hagen.', en: 'Renovation of the main hall, equipment for the workshop, kitchen, and garden gazebos.' },
  'grants.budget.item2.title': { pl: 'Program Wolontariatu', no: 'Frivillighetsprogram', en: 'Volunteer program' },
  'grants.budget.item2.desc': { pl: 'Fundusz dojazdów, Akademia Wolontariatu, ubezpieczenia i koordynacja.', no: 'Reisefond, Frivillighetsakademi, forsikring og koordinering.', en: 'Travel fund, Volunteer Academy, insurance, and coordination.' },
  'grants.budget.item3.title': { pl: 'Program kulturalny', no: 'Kulturprogram', en: 'Cultural program' },
  'grants.budget.item3.desc': { pl: 'Organizacja jarmarków (2/rok) oraz cyklu warsztatów i wystaw.', no: 'Organisering av markeder (2/år) samt en serie workshoper og utstillinger.', en: 'Organization of fairs (2/year) and a cycle of workshops and exhibitions.' },
  'grants.budget.quote': { pl: '"Inwestując w wolontariuszy, inwestujecie w trwały system zmiany. Każda godzina wsparcia zamienia się w godziny nauki i dobra wspólnego."', no: '«Ved å investere i frivillige investerer dere i et varig system for endring. Hver time med støtte blir til timer med læring og felles beste.»', en: '"By investing in volunteers, you are investing in a lasting system of change. Every hour of support turns into hours of learning and common good."' },
  'grants.support.btn': { pl: 'Wesprzyj naszą misję', no: 'Støtt vårt samfunnsoppdrag', en: 'Support our mission' },
  'grants.membership.title': { pl: 'Zostań członkiem', no: 'Bli medlem', en: 'Become a member' },
  'grants.membership.fee.label': { pl: 'Składka roczna', no: 'Årlig medlemsavgift', en: 'Annual fee' },
  'grants.membership.fee.value': { pl: '500 NOK', no: '500 NOK', en: '500 NOK' },
  'grants.membership.thanks': { pl: 'Kuźnia Talentów Skandii zyskuje, dzięki Tobie!', no: 'Skandias Talentmie vokser takket være deg!', en: 'Skandias Talent Forge grows thanks to you!' },
  'grants.membership.access': { pl: 'Za jedyne 500 kr rocznie zyskujesz dostęp do:', no: 'For bare 500 kr i året får du tilgang til:', en: 'For only 500 kr a year you gain access to:' },
  'grants.membership.list1': { pl: 'warsztatów, kursów i zajęć artystycznych', no: 'workshoper, kurs og kunstneriske aktiviteter', en: 'workshops, courses, and artistic activities' },
  'grants.membership.list2': { pl: 'możliwości rozwoju osobistego i zawodowego', no: 'muligheter for personlig og profesjonell utvikling', en: 'opportunities for personal and professional development' },
  'grants.membership.list3': { pl: 'spotkań z inspirującymi ludźmi', no: 'møter med inspirerende mennesker', en: 'meetings with inspiring people' },
  'grants.membership.list4': { pl: 'wyjątkowych wydarzeń dla całej rodziny', no: 'unike arrangementer for hele familien', en: 'unique events for the whole family' },
  'grants.membership.symbolic': { pl: 'To ogrom możliwości za symboliczną składkę członkowską!', no: 'Dette er enorme muligheter for en symbolsk medlemsavgift!', en: 'These are huge opportunities for a symbolic membership fee!' },
  'grants.payment.title': { pl: 'Dane do płatności', no: 'Betalingsinformasjon', en: 'Payment information' },
  'grants.payment.recipient': { pl: 'Odbiorca:', no: 'Mottaker:', en: 'Recipient:' },
  'grants.payment.vipps': { pl: 'Vipps:', no: 'Vipps:', en: 'Vipps:' },
  'grants.payment.bank': { pl: 'Bank:', no: 'Bank:', en: 'Bank:' },
  'grants.payment.titleLabel': { pl: 'Tytuł przelewu:', no: 'Betalingsmelding:', en: 'Transfer title:' },
  'grants.payment.titleValue': { pl: '„Składka członkowska – imię i nazwisko”', no: '«Medlemskontingent – fornavn og etternavn»', en: '"Membership fee – first and last name"' },
  'grants.how.title': { pl: 'Jak zostać członkiem?', no: 'Hvordan bli medlem?', en: 'How to become a member?' },
  'grants.how.step1.title': { pl: 'Wpłać składkę', no: 'Betal kontingenten', en: 'Pay the fee' },
  'grants.how.step1.desc': { pl: 'Wpłać 500 kr na konto lub przez Vipps (#968883).', no: 'Betal 500 kr til konto eller via Vipps (#968883).', en: 'Pay 500 kr to account or via Vipps (#968883).' },
  'grants.how.step1.details': { pl: 'Skandias Talentsmie\nBank: DNB\nKonto: 1520 23 71008\nTytuł: „Składka członkowska – imię i nazwisko”', no: 'Skandias Talentsmie\nBank: DNB\nKonto: 1520 23 71008\nBetalingsmelding: «Medlemskontingent – fornavn og etternavn»', en: 'Skandias Talentsmie\nBank: DNB\nAccount: 1520 23 71008\nTitle: "Membership fee – first and last name"' },
  'grants.how.step2.title': { pl: 'Wyślij potwierdzenie', no: 'Send bekreftelse', en: 'Send confirmation' },
  'grants.how.step2.desc': { pl: 'Wyślij nam wiadomość prywatną, e-mail lub SMS z potwierdzeniem przelewu.', no: 'Send oss en privat melding, e-post eller SMS med bekreftelse på overføringen.', en: 'Send us a private message, email, or SMS with transfer confirmation.' },
  'grants.how.step2.contact': { pl: 'SMS: +47 948 03 464\nEmail: agder@skandiatalentsmie.no', no: 'SMS: +47 948 03 464\nE-post: agder@skandiatalentsmie.no', en: 'SMS: +47 948 03 464\nEmail: agder@skandiatalentsmie.no' },
  'grants.how.step3.title': { pl: 'Gotowe!', no: 'Ferdig!', en: 'Done!' },
  'grants.how.step3.desc': { pl: 'Otrzymasz od nas potwierdzenie członkostwa oraz dostęp do wszystkich korzyści.', no: 'Du vil motta en bekreftelse på medlemskap fra oss og få tilgang til alle fordeler.', en: 'You will receive a membership confirmation from us and access to all benefits.' },
  'grants.footer.joinNow': { pl: 'Dołącz już dziś i zapewnij sobie oraz swojej rodzinie dostęp do wszystkiego, co najlepsze w Skandias Talentsmie!', no: 'Bli med i dag og sikre deg og din familie tilgang til det beste fra Skandias Talentsmie!', en: 'Join today and ensure you and your family access to the best of Skandias Talentsmie!' },
  'grants.footer.contactBtn': { pl: 'Kontakt z nami', no: 'Kontakt oss', en: 'Contact us' },

  // JoinUs Page
  'join.title': { pl: 'Dołącz do naszej kuźni!', no: 'Bli med i vår smie!', en: 'Join our forge!' },
  'join.subtitle': { pl: 'Masz duszę artysty? Tworzysz coś wyjątkowego własnymi rękami? Skandias Talentsmie to przestrzeń dla wszystkich, którzy chcą rozwijać swoje pasje i dzielić się nimi z innymi.', no: 'Har du en kunstnerisk sjel? Skaper du noe unikt med egne hender? Skandias Talentsmie er et rom for alle som ønsker å utvikle sine lidenskaper og dele dem med andre.', en: 'Do you have an artist\'s soul? Do you create something unique with your own hands? Skandias Talentsmie is a space for everyone who wants to develop their passions and share them with others.' },
  'join.why.title': { pl: 'Dlaczego warto?', no: 'Hvorfor er det verdt det?', en: 'Why join us?' },
  'join.why.1': { pl: 'Twoja pasja stanie się widoczna – pokaż światu swój talent.', no: 'Din lidenskap vil bli synlig – vis verden ditt talent.', en: 'Your passion will become visible – show the world your talent.' },
  'join.why.2': { pl: 'Pomożesz innym – unikatowe rzeczy są coraz bardziej poszukiwane.', no: 'Du vil hjelpe andre – unike ting er stadig mer ettertraktet.', en: 'You will help others – unique things are increasingly sought after.' },
  'join.why.3': { pl: 'Znajdziesz klientów i współpracowników.', no: 'Du vil finne kunder og samarbeidspartnere.', en: 'You will find customers and collaborators.' },
  'join.why.4': { pl: 'Docenią Twoją pracę – rękodzieło z duszą wygrywa z masówką.', no: 'De vil sette pris på ditt arbeid – håndverk med sjel vinner over masseproduksjon.', en: 'They will appreciate your work – handicrafts with soul win over mass production.' },
  'join.offer.title': { pl: 'Co oferujemy?', no: 'Hva tilbyr vi?', en: 'What do we offer?' },
  'join.offer.1': { pl: 'Promocję twórców i pomoc w docieraniu do odbiorców.', no: 'Promotering av skapere og hjelp til å nå ut til publikum.', en: 'Promotion of creators and help in reaching audiences.' },
  'join.offer.2': { pl: 'Organizację warsztatów i wydarzeń regionalnych.', no: 'Organisering av workshoper og regionale arrangementer.', en: 'Organization of workshops and regional events.' },
  'join.offer.3': { pl: 'Budowanie społeczności, w której każdy może się rozwijać.', no: 'Bygge et fellesskap der alle kan utvikle seg.', en: 'Building a community where everyone can develop.' },
  'join.offer.4': { pl: 'Wspieranie pasjonatów w budowaniu rozpoznawalności.', no: 'Støtte lidenskapelige i å bygge anerkjennelse.', en: 'Supporting enthusiasts in building recognition.' },
  'join.steps.title': { pl: 'Wystarczy tylko:', no: 'Alt som kreves er:', en: 'All it takes is:' },
  'join.steps.1': { pl: 'Wypełnić formularz zgłoszeniowy', no: 'Fyll ut søknadsskjemaet', en: 'Fill out the application form' },
  'join.steps.2': { pl: 'Dokonać wpłaty członkowskiej', no: 'Betal medlemskontingenten', en: 'Pay the membership fee' },
  'join.steps.3': { pl: 'I gotowe!', no: 'Og ferdig!', en: 'And you\'re done!' },
  'join.action.title': { pl: 'Gotowy by zaprezentować swój talent?', no: 'Klar for å presentere ditt talent?', en: 'Ready to present your talent?' },
  'join.action.desc': { pl: 'Skontaktuj się z nami bezpośrednio przez nasz oficjalny formularz.', no: 'Kontakt oss direkte via vårt offisielle skjema.', en: 'Contact us directly through our official form.' },
  'join.action.btn': { pl: 'Przejdź do kontaktu', no: 'Gå til kontakt', en: 'Go to contact' },

  // JoinUs Categories
  'join.cat.art.title': { pl: 'Rękodzieło i sztuka', no: 'Håndverk og kunst', en: 'Handicraft & Art' },
  'join.cat.art.items': { pl: 'Malowanie obrazów (oleje, akwarele, akryle); Gobeliny, haft, ikony i sztuka sakralna; Rysunek, maski, dekoracje teatralne', no: 'Maleri (olje, akvarell, akryl); Gobeliner, broderi, ikoner og sakral kunst; Tegning, masker, teaterdekorasjoner', en: 'Painting (oils, watercolors, acrylics); Tapestries, embroidery, icons and sacred art; Drawing, masks, theater decorations' },
  'join.cat.decor.title': { pl: 'Dekoracje i ozdoby', no: 'Dekorasjoner og ornamenter', en: 'Decorations & Ornaments' },
  'join.cat.decor.items': { pl: 'Wianki, łapacze snów, figurki i rzeźby; Bukiety kwiatowe, świece, ozdoby świąteczne; Makrama i plecionki', no: 'Kranser, drømmefangere, figurer og skulpturer; Blomsterbuketter, lys, julepynt; Makramé og fletting', en: 'Wreaths, dreamcatchers, figurines and sculptures; Flower bouquets, candles, Christmas ornaments; Macrame and braids' },
  'join.cat.jewelry.title': { pl: 'Biżuteria i akcesoria', no: 'Smykker og tilbehør', en: 'Jewelry & Accessories' },
  'join.cat.jewelry.items': { pl: 'Naszyjniki, pierścionki, broszki; Spinki, opaski, torebki handmade', no: 'Halskjeder, ringer, brosjer; Hårklemmer, hodebånd, håndlagde vesker', en: 'Necklaces, rings, brooches; Hair clips, headbands, handmade bags' },
  'join.cat.textiles.title': { pl: 'Tekstylia i szycie', no: 'Tekstiler og søm', en: 'Textiles & Sewing' },
  'join.cat.textiles.items': { pl: 'Ubrania, szaliki, rękawiczki; Haft, szydełko, patchwork; Stroje historyczne, maskotki', no: 'Klær, skjerf, hansker; Broderi, hekling, patchwork; Historiske kostymer, kosedyr', en: 'Clothes, scarves, gloves; Embroidery, crochet, patchwork; Historical costumes, soft toys' },
  'join.cat.home.title': { pl: 'Domowe wyroby', no: 'Hjemmelagde produkter', en: 'Homemade Products' },
  'join.cat.home.items': { pl: 'Torty, pieczywo, czekoladki; Wędliny, sery, nalewki; Przetwory i kiszonki', no: 'Kaker, brød, sjokolade; Kjøttvarer, oster, tinkturer; Syltetøy og fermentert mat', en: 'Cakes, bread, chocolates; Cold cuts, cheeses, tinctures; Preserves and pickles' },
  'join.cat.natural.title': { pl: 'Produkty naturalne', no: 'Naturlige produkter', en: 'Natural Products' },
  'join.cat.natural.items': { pl: 'Mydła, kosmetyki, olejki; Kule do kąpieli, perfumy', no: 'Såper, kosmetikk, oljer; Badekuler, parfymer', en: 'Soaps, cosmetics, oils; Bath bombs, perfumes' },
  'join.cat.craft.title': { pl: 'Rzemiosło użytkowe', no: 'Brukshåndverk', en: 'Functional Craft' },
  'join.cat.craft.items': { pl: 'Meble, dekoracje z drewna; Kosze wiklinowe, kowalstwo', no: 'Møbler, tredekorasjoner; Kurver, smiing', en: 'Furniture, wood decorations; Baskets, blacksmithing' },
  'join.cat.digital.title': { pl: 'Sztuka cyfrowa i foto', no: 'Digital kunst og foto', en: 'Digital Art & Photo' },
  'join.cat.digital.items': { pl: 'Fotografia artystyczna i portretowa; Filmy, animacje, kaligrafia', no: 'Kunst- og portrettfotografering; Filmer, animasjoner, kalligrafi', en: 'Artistic and portrait photography; Films, animations, calligraphy' },

  // About Page
  'about.narrative.subtitle': { pl: 'Opowieść o nas', no: 'Vår historie', en: 'Our Story' },
  'about.narrative.title': { pl: 'Skandias Talentsmie — Kim jesteśmy i dlaczego jesteśmy potrzebni', no: 'Skandias Talentsmie — Hvem vi er og hvorfor vi trengs', en: 'Skandias Talentsmie — Who we are and why we are needed' },
  'about.narrative.quote1': { pl: 'W Norwegii można żyć bezpiecznie, pracować uczciwie, płacić podatki, być „samowystarczalnym” — i jednocześnie każdego dnia czuć się samotnym, niewidzialnym, jakby się stało na korytarzu między dwoma światami.', no: 'I Norge kan man leve trygt, jobbe ærlig, betale skatt, være «selvforsynt» — og samtidig føle seg ensom hver dag, usynlig, som om man står i korridoren mellom to verdener.', en: 'In Norway, one can live safely, work honestly, pay taxes, be "self-sufficient" — and at the same time feel lonely every day, invisible, as if standing in a corridor between two worlds.' },
  'about.narrative.quote2': { pl: 'Tego nie widać w statystykach. Ale to widać w oczach ludzi, którzy po pracy nie mają dokąd pójść, z kim porozmawiać, komu powiedzieć: „jest mi ciężko”.', no: 'Dette vises ikke i statistikkene. Men det vises i øynene til folk som ikke har noe sted å gå etter jobb, ingen å snakke med, ingen å si til: «det er tungt for meg».', en: 'This is not visible in statistics. But it is visible in the eyes of people who have nowhere to go after work, no one to talk to, no one to say: "it\'s hard for me".' },
  'about.narrative.highlight': { pl: 'I właśnie tam — w tej cichej, codziennej samotności — narodziło się Skandias Talentsmie.', no: 'Og akkurat der — i denne stille, hverdagsensomheten — ble Skandias Talentsmie født.', en: 'And right there — in that quiet, daily loneliness — Skandias Talentsmie was born.' },
  'about.narrative.origin': { pl: 'Nie z pomysłu „na organizację”. Tylko z potrzeby. Z serca. Z życia.', no: 'Ikke fra en idé om «en organisasjon». Bare fra behov. Fra hjertet. Fra livet.', en: 'Not from an idea of "an organization". Just from need. From the heart. From life.' },
  'about.narrative.originList1': { pl: 'Z rozmów z kobietami, które dźwigają wszystko same.', no: 'Fra samtaler med kvinner som bærer alt alene.', en: 'From conversations with women who carry everything alone.' },
  'about.narrative.originList2': { pl: 'Z wiadomości od ludzi, którzy nie mają tu rodziny.', no: 'Fra meldinger fra folk som ikke har familie her.', en: 'From messages from people who have no family here.' },
  'about.narrative.originList3': { pl: 'Z seniorów, którzy zostali w Norwegii na dłużej, niż planowali.', no: 'Fra seniorer som ble i Norge lenger enn de planla.', en: 'From seniors who stayed in Norway longer than they planned.' },
  'about.narrative.originList4': { pl: 'Z mężczyzn pracujących fizycznie, którym brakuje sensu w ciszy domu.', no: 'Fra menn i fysisk arbeid som mangler mening i hjemmets stillhet.', en: 'From men in physical work who lack meaning in the silence of home.' },
  'about.narrative.conclusion': { pl: 'Skandias Talentsmie powstało po to, żeby człowiek przestał być sam.', no: 'Skandias Talentsmie ble til for at mennesket skal slutte å være alene.', en: 'Skandias Talentsmie was created so that people stop being alone.' },
  'about.who.subtitle': { pl: 'Kim jesteśmy', no: 'Hvem vi er', en: 'Who we are' },
  'about.who.title': { pl: 'Wspólnota Słowian w Agder', no: 'Slavisk fellesskap i Agder', en: 'Slavic Community in Agder' },
  'about.who.desc1': { pl: 'Jesteśmy stowarzyszeniem non-profit, zbudowanym przez osoby pochodzenia słowiańskiego mieszkające w Norwegii — w szczególności w regionie Agder (Grimstad, Arendal, Tvedestrand).', no: 'Vi er en ideell organisasjon bygget av folk med slavisk bakgrunn som bor i Norge — spesielt i Agder-regionen (Grimstad, Arendal, Tvedestrand).', en: 'We are a non-profit association built by people of Slavic origin living in Norway — specifically in the Agder region (Grimstad, Arendal, Tvedestrand).' },
  'about.who.desc2': { pl: 'Łączymy ludzi z Polski, Ukrainy, Czech, Słowacji, Bułgarii, Białorusi i krajów bałkańskich. To społeczność ogromna, a jednocześnie często „niewidzialna”.', no: 'Vi forener folk fra Polen, Ukraina, Tsjekkia, Slovakia, Bulgaria, Hviterussland og Balkan-landene. Det er et enormt samfunn, men ofte «usynlig».', en: 'We unite people from Poland, Ukraine, Czech Republic, Slovakia, Bulgaria, Belarus, and Balkan countries. It is a huge community, yet often "invisible".' },
  'about.for.subtitle': { pl: 'Dla kogo to robimy', no: 'Hvem gjør vi det for', en: 'Who we do it for' },
  'about.for.title': { pl: 'Dla tych, którzy nie krzyczą o pomoc', no: 'For de som ikke roper om hjelp', en: 'For those who don\'t scream for help' },
  'about.for.item1': { pl: 'Osoby doświadczające samotności i izolacji', no: 'Personer som opplever ensomhet og isolasjon', en: 'People experiencing loneliness and isolation' },
  'about.for.item2': { pl: 'Samotnie wychowujący dzieci', no: 'Aleneforeldre', en: 'Single parents' },
  'about.for.item3': { pl: 'Opiekunowie bliskich i seniorzy', no: 'Pårørende og eldre', en: 'Caregivers and seniors' },
  'about.for.item4': { pl: 'Osoby po traumie i przymusowej migracji', no: 'Personer etter traumer og tvungen migrasjon', en: 'People after trauma and forced migration' },
  'about.for.item5': { pl: 'Młodzież wychowująca się między kulturami', no: 'Ungdom som vokser opp mellom kulturer', en: 'Youth growing up between cultures' },
  'about.why.subtitle': { pl: 'Dlaczego to jest ważne', no: 'Hvorfor dette er viktig', en: 'Why this is important' },
  'about.why.title': { pl: 'Ręce i serce pracują razem', no: 'Hender og hjerte jobber sammen', en: 'Hands and heart work together' },
  'about.why.quote': { pl: '„Największe dramaty w bogatych krajach dzieją się po cichu. Nie w braku chleba — tylko w braku człowieka obok.”', no: '«De største dramaene i rike land skjer i det stille. Ikke i mangelen på brød — men i mangelen på et menneske ved siden av.»', en: '"The greatest dramas in wealthy countries happen quietly. Not in the lack of bread — but in the lack of a human being nearby."' },
  'about.why.desc1': { pl: 'Samotność, wykluczenie i rozpad więzi to nie jest „miękki temat”. To kosztuje społeczeństwo zdrowie psychiczne i poczucie bezpieczeństwa.', no: 'Ensomhet, utestenging og oppløsning av bånd er ikke et «mykt tema». Det koster samfunnet psykisk helse og trygghetsfølelse.', en: 'Loneliness, exclusion, and the breakdown of bonds is not a "soft topic". It costs society mental health and a sense of security.' },
  'about.why.desc2': { pl: 'W kulturach słowiańskich rzemiosło to język, który przechodzi ponad barierą słów. Kiedy trzymasz w ręku glinę, igłę lub pędzel — łatwiej zaczynasz mówić.', no: 'I slaviske kulturer er håndverk et språk som går utover ord-barrierer. Når du holder leire, en nål eller en pensel — begynner du lettere å snakke.', en: 'In Slavic cultures, craftsmanship is a language that goes beyond the barrier of words. When you hold clay, a needle, or a brush — you begin to speak more easily.' },
  'about.why.desc3': { pl: 'A kiedy zaczynasz mówić — przestajesz być sam.', no: 'Og når du begynner å snakke — slutter du å være alene.', en: 'And when you begin to speak — you stop being alone.' },
  'about.goals.subtitle': { pl: 'Nasze cele', no: 'Våre mål', en: 'Our Goals' },
  'about.goals.1': { pl: 'Przeciwdziałać samotności i izolacji społecznej.', no: 'Motvirke ensomhet og sosial isolasjon.', en: 'Counter loneliness and social isolation.' },
  'about.goals.2': { pl: 'Budować realną integrację między kulturą słowiańską i skandynawską – bez konfliktu, z szacunkiem i dumą.', no: 'Bygge reell integrering mellom slavisk og skandinavisk kultur – uten konflikt, med respekt og stolthet.', en: 'Build real integration between Slavic and Scandinavian culture – without conflict, with respect and pride.' },
  'about.goals.3': { pl: 'Wzmacniać zdrowie psychiczne poprzez relacje, sprawczość i poczucie sensu.', no: 'Styrke psykisk helse gjennom relasjoner, mestring og mening.', en: 'Strengthen mental health through relationships, agency, and a sense of meaning.' },
  'about.goals.4': { pl: 'Wydobywać i promować talenty rzemieślników, rękodzielników i twórców — tych „z cienia”.', no: 'Trekke frem og fremme talenter hos håndverkere og skapere — de «fra skyggen».', en: 'Extract and promote the talents of artisans, craftspeople, and creators — those "from the shadows".' },
  'about.goals.5': { pl: 'Tworzyć most międzypokoleniowy: starsi przekazują tradycję, młodzi wnoszą kompetencje cyfrowe i energię.', no: 'Skape en bro mellom generasjoner: eldre gir tradisjon videre, unge bidrar med digital kompetanse og energi.', en: 'Create an intergenerational bridge: seniors pass on tradition, youth bring digital competence and energy.' },
  'about.goals.6': { pl: 'Budować sieć miejsc w Norwegii, gdzie kultura i twórczość stają się narzędziem wspólnoty.', no: 'Bygge et nettverk av steder i Norge hvor kultur og kreativitet blir et verktøy for fellesskap.', en: 'Build a network of places in Norway where culture and creativity become a tool for community.' },
  'about.impact.subtitle': { pl: 'Nasz wkład', no: 'Vårt bidrag', en: 'Our Contribution' },
  'about.impact.title': { pl: 'Nie jesteśmy „organizacją na papierze”. Jesteśmy ruchem ludzi.', no: 'Vi er ikke en «organisasjon på papiret». Vi er en folkebevegelse.', en: 'We are not an "organization on paper". We are a movement of people.' },
  'about.impact.desc': { pl: 'Przy około 95 aktywnościach rocznie, nasi wolontariusze wkładają ponad 5 700 godzin pracy społecznej. To energia społeczna — największy kapitał regionu.', no: 'Med rundt 95 aktiviteter i året legger våre frivillige ned over 5 700 timer samfunnsarbeid. Det er sosial energi — regionens største kapital.', en: 'With about 95 activities per year, our volunteers contribute over 5,700 hours of social work. This is social energy — the region\'s greatest capital.' },
  'about.stats.members': { pl: 'Członków Składkowych', no: 'Betalende medlemmer', en: 'Paying Members' },
  'about.stats.sympathizers': { pl: 'Sympatyków', no: 'Sympatisører', en: 'Sympathizers' },
  'about.stats.volunteers': { pl: 'Aktywnych Wolontariuszy', no: 'Aktive frivillige', en: 'Active Volunteers' },
  'about.stats.hours': { pl: 'Godzin Społecznych', no: 'Dugnadstimer', en: 'Social Hours' },
  'about.benefits.subtitle': { pl: 'Wpływ Społeczny', no: 'Samfunnspåvirkning', en: 'Social Impact' },
  'about.benefits.title': { pl: 'Co region Agder ma z naszych działań?', no: 'Hva får Agder-regionen ut av våre aktiviteter?', en: 'What does the Agder region gain from our activities?' },
  'about.benefits.1.title': { pl: 'Mniej samotności', no: 'Mindre ensomhet', en: 'Less loneliness' },
  'about.benefits.1.desc': { pl: 'Mniej kryzysów psychicznych w regionie.', no: 'Færre psykiske kriser i regionen.', en: 'Fewer mental crises in the region.' },
  'about.benefits.2.title': { pl: 'Więcej relacji', no: 'Flere relasjoner', en: 'More relationships' },
  'about.benefits.2.desc': { pl: 'Większe bezpieczeństwo społeczne i zaufanie.', no: 'Større sosial trygghet og tillit.', en: 'Greater social security and trust.' },
  'about.benefits.3.title': { pl: 'Integracja w praktyce', no: 'Integrering i praksis', en: 'Integration in practice' },
  'about.benefits.3.desc': { pl: 'Lepsze funkcjonowanie migrantów w lokalnej społeczności.', no: 'Bedre fungering av migranter i lokalmiljøet.', en: 'Better functioning of migrants in the local community.' },
  'about.benefits.4.title': { pl: 'Aktywizacja', no: 'Aktivering', en: 'Activation' },
  'about.benefits.4.desc': { pl: 'Większa samodzielność i sprawczość osób wykluczonych.', no: 'Større selvstendighet og mestringsevne hos ekskluderte.', en: 'Greater independence and agency of excluded individuals.' },
  'about.benefits.5.title': { pl: 'Przestrzeń dla talentów', no: 'Plass for talenter', en: 'Space for talents' },
  'about.benefits.5.desc': { pl: 'Rozwój kultury i lokalnej kreatywności.', no: 'Utvikling av kultur og lokal kreativitet.', en: 'Development of culture and local creativity.' },
  'about.benefits.6.title': { pl: 'Mosty międzypokoleniowe', no: 'Generasjonsbroer', en: 'Intergenerational bridges' },
  'about.benefits.6.desc': { pl: 'Młodzi nie tracą korzeni, starsi odzyskują sens.', no: 'Unge mister ikke røttene sine, eldre gjenvinner mening.', en: 'Youth don\'t lose roots, seniors regain meaning.' },
  'about.whynow.title': { pl: 'Dlaczego jesteśmy potrzebni teraz?', no: 'Hvorfor trengs vi nå?', en: 'Why are we needed now?' },
  'about.whynow.desc': { pl: 'Bo Agder — jak cała Norwegia — zmienia się. Coraz więcej ludzi żyje obok siebie, a coraz mniej ze sobą. Coraz więcej ciszy w domach.', no: 'Fordi Agder — som hele Norge — endrer seg. Stadig flere lever ved siden av hverandre, men færre med hverandre. Mer stillhet i hjemmene.', en: 'Because Agder — like all of Norway — is changing. More and more people live side by side, and fewer with each other. More silence in homes.' },
  'about.whynow.highlight': { pl: '„A my robimy coś, co jest dziś bezcenne: przywracamy człowiekowi miejsce przy stole.”', no: '«Og vi gjør noe som er uvurderlig i dag: vi gir mennesket plassen tilbake ved bordet.»', en: '"And we are doing something that is priceless today: we are giving people their place back at the table."' },
  'about.vision.title': { pl: 'Nasza Wizja', no: 'Vår visjon', en: 'Our Vision' },
  'about.vision.desc': { pl: 'Centrum Sztuki i Integracji Skandias Talentsmie w Songe. Chcemy stworzyć ogólnonorweską sieć miejsc, gdzie kultura i wspólnotą będą ratować przed samotnością.', no: 'Skandias Talentsmie Senter for Kunst og Integrering i Songe. Vi ønsker å skape et landsomfattende nettverk av steder hvor kultur og fellesskap vil redde folk fra ensomhet.', en: 'Skandias Talentsmie Center for Art and Integration in Songe. We want to create a Norway-wide network of places where culture and community will save people from loneliness.' },
  'about.slavic.title': { pl: 'Kraje Słowiańskie w naszej społeczności', no: 'Slaviske land i vårt fellesskap', en: 'Slavic Countries in our community' },
  'about.slavic.subtitle': { pl: 'Razem tworzymy wspólnotę, w której każdy talent ma swoje miejsce', no: 'Sammen skaper vi et fellesskap hvor hvert talent har sin plass', en: 'Together we create a community where every talent has its place' },
  'about.slavic.group': { pl: 'Słowianie', no: 'Slavere', en: 'Slavs' },
  'about.footer.quote': { pl: '„Skandias Talentsmie istnieje po to, by talent stał się widoczny, a człowiek przestał być sam — a dzięki temu społeczeństwo staje się zdrowsze.”', no: '«Skandias Talentsmie eksisterer for at talent skal bli synlig og mennesket slutte å være alene — og dermed blir samfunnet sunnere.»', en: '"Skandias Talentsmie exists so that talent becomes visible and people stop being alone — and thus society becomes healthier."' },

  // Membership Page
  'membership.title': { pl: 'Członkostwo i koordynatorzy', no: 'Medlemskap og koordinatorer', en: 'Membership & Coordinators' },
  'membership.subtitle': { pl: 'Skandias Talentsmie to więcej niż stowarzyszenie – to żywa społeczność pełna pasji. Jeśli masz talent, jeśli tworzysz – to jest miejsce, w którym Twój dar zakwitnie! 🌸', no: 'Skandias Talentsmie er mer enn en forening – det er et levende fellesskap fullt av lidenskap. Hvis du har et talent, hvis du skaper – er dette stedet hvor din gave vil blomstre! 🌸', en: 'Skandias Talentsmie is more than an association – it is a living community full of passion. If you have a talent, if you create – this is the place where your gift will bloom! 🌸' },
  'membership.benefits.subtitle': { pl: 'Zostań członkiem', no: 'Bli medlem', en: 'Become a Member' },
  'membership.benefits.title': { pl: 'Twoje korzyści', no: 'Dine fordeler', en: 'Your Benefits' },
  'membership.benefits.1': { pl: 'Promocja Twojej twórczości – strona, media społecznościowe i kiermasze.', no: 'Promotering av ditt kreative arbeid – nettside, sosiale medier og messer.', en: 'Promotion of your creativity – website, social media, and fairs.' },
  'membership.benefits.2': { pl: 'Udział w targach i jarmarkach w całej Norwegii.', no: 'Deltakelse i messer og markeder over hele Norge.', en: 'Participation in fairs and markets throughout Norway.' },
  'membership.benefits.3': { pl: 'Warsztaty i kursy – ucz się nowych technik lub prowadź własne zajęcia.', no: 'Workshoper og kurs – lær nye teknikker eller hold dine egne klasser.', en: 'Workshops and courses – learn new techniques or lead your own classes.' },
  'membership.benefits.4': { pl: 'Dzielenie się talentem – my zapewniamy miejsce i materiały, Ty wiedzę.', no: 'Deling av talent – vi sørger for plass og materialer, du for kunnskap.', en: 'Sharing talent – we provide space and materials, you provide knowledge.' },
  'membership.benefits.5': { pl: 'Szkolenia i rozwój – nauka sprzedaży, budowania marki i marketingu.', no: 'Opplæring og utvikling – lær salg, merkevarebygging og markedsføring.', en: 'Training and development – learn sales, branding, and marketing.' },
  'membership.benefits.6': { pl: 'Zniżki i rabaty w sklepach z materiałami artystycznymi i narzędziami.', no: 'Rabatter i butikker med kunstmateriell og verktøy.', en: 'Discounts in stores with art materials and tools.' },
  'membership.benefits.7': { pl: 'Sieć kontaktów – współpraca z innymi artystami i rzemieślnikami.', no: 'Nettverk – samarbeid med andre kunstnere og håndverkere.', en: 'Networking – collaboration with other artists and craftspeople.' },
  'membership.benefits.8': { pl: 'Granty i dofinansowania – pomoc w uzyskaniu wsparcia finansowego.', no: 'Tilskudd og finansiering – hjelp til å få økonomisk støtte.', en: 'Grants and funding – help in obtaining financial support.' },
  'membership.benefits.9': { pl: 'Możliwość zostania koordynatorem regionalnym.', no: 'Mulighet til å bli regional koordinator.', en: 'Opportunity to become a regional coordinator.' },
  'membership.benefits.10': { pl: 'Galeria online – Twoja własna przestrzeń wystawowa.', no: 'Galleri på nett – ditt eget utstillingsvindu.', en: 'Online gallery – your own exhibition space.' },
  'membership.benefits.11': { pl: 'Wspólne projekty artystyczne, kolekcje i wystawy.', no: 'Felles kunstprosjekter, kolleksjoner og utstillinger.', en: 'Joint art projects, collections, and exhibitions.' },
  'membership.benefits.12': { pl: 'Newsletter z inspiracjami i ofertami tylko dla członków.', no: 'Nyhetsbrev med inspirasjon og tilbud kun for medlemmer.', en: 'Newsletter with inspiration and offers exclusively for members.' },
  'membership.joinBtn': { pl: 'Dołącz do nas', no: 'Bli med oss', en: 'Join us' },
  'membership.coordinator.subtitle': { pl: 'Projekt 13 × 13', no: 'Prosjekt 13 × 13', en: 'Project 13 × 13' },
  'membership.coordinator.title': { pl: 'Zostań koordynatorem', no: 'Bli koordinator', en: 'Become a Coordinator' },
  'membership.coordinator.desc': { pl: 'Szukamy liderów w każdym z 13 województw Norwegii. Koordynator to serce i twarz regionalnej filii. Szukamy osób z energią, które kochają jednoczyć ludzi i inspirować innych.', no: 'Vi søker ledere i hvert av de 13 fylkene i Norge. En koordinator er hjertet og ansiktet til en regional filial. Vi ser etter folk med energi som elsker å forene folk og inspirere andre.', en: 'We are looking for leaders in each of Norway\'s 13 counties. A coordinator is the heart and face of a regional branch. We are looking for people with energy who love uniting people and inspiring others.' },
  'membership.coordinator.role.title': { pl: 'Twoja rola:', no: 'Din rolle:', en: 'Your Role:' },
  'membership.coordinator.role.1': { pl: 'Organizacja warsztatów i spotkań lokalnych.', no: 'Organisering av workshoper og lokale møter.', en: 'Organizing workshops and local meetings.' },
  'membership.coordinator.role.2': { pl: 'Współpraca z artystami i przygotowywanie jarmarków.', no: 'Samarbeid med kunstnere og forberedelse av markeder.', en: 'Collaboration with artists and preparation of fairs.' },
  'membership.coordinator.role.3': { pl: 'Promowanie talentów i inicjatyw w regionie.', no: 'Promotering av talenter og initiativ i regionen.', en: 'Promoting talents and initiatives in the region.' },
  'membership.support.title': { pl: 'Jakie wsparcie oferujemy?', no: 'Hvilken støtte tilbyr vi?', en: 'What support do we offer?' },
  'membership.support.desc': { pl: 'Nikt nie działa sam! Każda filia otrzyma od nas:', no: 'Ingen jobber alene! Hver filial vil motta fra oss:', en: 'No one acts alone! Every branch will receive from us:' },
  'membership.support.1': { pl: 'Pomoc w promocji', no: 'Hjelp til promotering', en: 'Marketing support' },
  'membership.support.2': { pl: 'Finansowanie projektów', no: 'Finansiering av prosjekter', en: 'Project funding' },
  'membership.support.3': { pl: 'Dofinansowanie kiermaszy', no: 'Tilskudd til messer', en: 'Fair funding' },
  'membership.support.4': { pl: 'Know-how i materiały', no: 'Know-how og materiell', en: 'Know-how and materials' },
  'membership.steps.title': { pl: 'Wystarczy tylko:', no: 'Alt du trenger er:', en: 'All you need is:' },
  'membership.steps.1': { pl: 'Skopiować i wypełnić formularz zgłoszeniowy', no: 'Kopiere og fyll ut søknadsskjemaet', en: 'Copy and fill out the application form' },
  'membership.steps.2': { pl: 'Dokonać wpłaty członkowskiej', no: 'Betale medlemsavgift', en: 'Pay membership fee' },
  'membership.steps.3': { pl: 'I gotowe!', no: 'Og ferdig!', en: 'And you\'re done!' },
  'membership.volunteers.title': { pl: 'Potrzebujemy wolontariuszy!', no: 'Vi trenger frivillige!', en: 'We need volunteers!' },
  'membership.volunteers.desc': { pl: '„Nie każdy musi być koordynatorem – w każdej filii potrzebujemy wolontariuszy i pomocników. Każda para rąk się liczy: od prowadzenia warsztatów po pomoc w logistyce.”', no: '«Ikke alle trenger å være koordinator – i hver filial trenger vi frivillige og hjelpere. Hvert par hender teller: fra å holde workshoper til hjelp med logistikk.»', en: '"Not everyone has to be a coordinator – in every branch we need volunteers and helpers. Every pair of hands counts: from leading workshops to help with logistics."' },
  'membership.volunteers.tagline': { pl: 'Energia społeczna to nasz kapitał', no: 'Sosial energi er vår kapital', en: 'Social energy is our capital' },
  'membership.volunteers.btn': { pl: 'Zgłoś chęć pomocy', no: 'Meld deg som frivillig', en: 'Volunteer to help' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pl');

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
